---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
---
spring:
  config:
    activate:
      on-profile: int
words: I,You,He,She,It
